services:
  signing-tool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ftso-signing-tool
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data